import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import SupabaseProvider from "@/providers/SupabaseProvider";
import UserProvider from "@/providers/UserProvider";
import ModalProvider from "@/providers/ModalProvider";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       <SupabaseProvider>
          <UserProvider>
            <ModalProvider />
              <Sidebar>
                  {children}
              </Sidebar>
          </UserProvider>
       </SupabaseProvider>
      </body>
    </html>
  );
}
