import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import SupabaseProvider from "@/providers/SupabaseProvider";
import UserProvider from "@/providers/UserProvider";
import ModalProvider from "@/providers/ModalProvider";
import ToasterProvider from "@/providers/ToasterProvider";
import getSongsByUserId from "@/actions/getSongsByUserId";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 0;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userSongs = await getSongsByUserId();
  return (
    <html lang="en">
      <body>
       <SupabaseProvider>
        <ToasterProvider />
          <UserProvider>
            <ModalProvider />
              <Sidebar songs={userSongs}>
                  {children}
              </Sidebar>
          </UserProvider>
       </SupabaseProvider>
      </body>
    </html>
  );
}
